# Etapa 1: Build da aplicação
FROM eclipse-temurin:21-jdk AS builder
WORKDIR /app

# Copia os arquivos do projeto
COPY . .

# Compila o projeto usando Maven
RUN ./mvnw clean package -DskipTests

# Etapa 2: Imagem leve para produção
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copia o JAR gerado
COPY --from=builder /app/target/{{ENTRY}}.jar app.jar

# Expõe a porta padrão do Spring Boot
EXPOSE 8080

# Comando para iniciar a aplicação
CMD ["java", "-jar", "app.jar"]