FROM php:8.4.11-apache
WORKDIR /var/www/html
COPY . .
RUN apt-get update && apt-get install -y unzip libzip-dev && docker-php-ext-install zip pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install
CMD ["apache2-foreground"]