# Etapa 1: Build da aplicação
FROM gradle:8.7.0-jdk21 AS builder
WORKDIR /app

# Copia os arquivos do projeto
COPY . .

# Compila o projeto e gera o JAR
RUN gradle clean build -x test

# Etapa 2: Imagem leve para produção
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copia o JAR gerado
COPY --from=builder /app/build/libs/{{ENTRY}}.jar app.jar

# Expõe a porta padrão do Spring Boot
EXPOSE 8080

# Comando para iniciar a aplicação
CMD ["java", "-jar", "app.jar"]